package com.example.blackbox.sharing

import com.example.blackbox.BuildConfig

object SharingVersions {
    val APP_VERSION_CODE: Int = BuildConfig.VERSION_CODE
    val APP_VERSION_NAME: String = BuildConfig.VERSION_NAME

    val STATE_SCHEMA_VERSION: Int = BuildConfig.SHARING_STATE_SCHEMA_VERSION
    val PAYLOAD_VERSION: Int = BuildConfig.SHARING_PAYLOAD_VERSION
    val CONTACT_CARD_PREFIX: String = BuildConfig.SHARING_CONTACT_CARD_PREFIX
    val CONTACT_CARD_VERSION: Int = BuildConfig.SHARING_CONTACT_CARD_VERSION
    val IDENTITY_BUNDLE_VERSION: String = BuildConfig.SHARING_IDENTITY_BUNDLE_VERSION

    val ACL_CANONICAL_VERSION: String = BuildConfig.SHARING_CANONICAL_ACL_VERSION
    val PUSH_CANONICAL_VERSION: String = BuildConfig.SHARING_CANONICAL_PUSH_VERSION
    val PULL_CANONICAL_VERSION: String = BuildConfig.SHARING_CANONICAL_PULL_VERSION
    val SELF_STATUS_CANONICAL_VERSION: String = BuildConfig.SHARING_CANONICAL_SELF_STATUS_VERSION
    val CLEAR_CANONICAL_VERSION: String = BuildConfig.SHARING_CANONICAL_CLEAR_VERSION
    val CONTACT_CARD_CANONICAL_VERSION: String = BuildConfig.SHARING_CANONICAL_CONTACT_CARD_VERSION
    val PUSH_CONTEXT_VERSION: String = BuildConfig.SHARING_PUSH_CONTEXT_VERSION
    val RELAY_API_VERSION: String = BuildConfig.SHARING_RELAY_API_VERSION

    val SECURE_STORAGE_BLOB_VERSION: Int = BuildConfig.SHARING_SECURE_STORAGE_BLOB_VERSION
}
